name: CI

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
    types:
      - checks_requested

permissions:
  contents: read

jobs:
  check-stable:
    name: Check compilation on stable toolchain
    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: "-D warnings"

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy

      - name: Install cargo-hack
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack
          checksum: true

      - uses: Swatinem/rust-cache@v2.9.1

      - name: Check compilation
        run: cargo hack check --each-feature --all-targets

      - name: Run Clippy
        run: cargo clippy --all-features --all-targets

  check-msrv:
    name: Check compilation on MSRV toolchain
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Get MSRV from Cargo.toml
        shell: bash
        run: |
          msrv=$(yq -oy '.package.rust-version' Cargo.toml)
          echo "msrv=${msrv}" >> $GITHUB_ENV

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "${{ env.msrv }}"

      - uses: Swatinem/rust-cache@v2.9.1

      - name: Install cargo-hack
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack
          checksum: true

      - name: Run `cargo hack`
        shell: bash
        run: cargo hack check --each-feature --all-targets

  formatting:
    name: Check formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt

      - name: Check formatting
        shell: bash
        run: cargo +nightly fmt --all --check
